version: 2

jobs:
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/aero
    docker: 
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: aero-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: aero-{{ checksum "project.clj" }}
      - run: lein test
